CineTicketHub/Controllers/GenresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CineTicketHub.Enums;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CineTicketHub.Models;
using CineTicketHub.Models.Entities;
using Microsoft.AspNetCore.Authorization;

namespace CineTicketHub.Controllers
{
    [Authorize(Roles = "CONTENT_MANAGER")]
    public class GenresController : Controller
    {
        private readonly CineTicketHubContext _context;

        public GenresController(CineTicketHubContext context)
        {
            _context = context;
        }

        // GET: Genres
        public async Task<IActionResult> Index()
        {
            return View(await _context.Genres.ToListAsync());
        }

        // GET: Genres/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var genre = await _context.Genres
                .FirstOrDefaultAsync(m => m.Id == id);
            if (genre == null)
            {
                return NotFound();
            }

            return View(genre);
        }

        // GET: Genres/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Genres/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] Genre genre)
        {
            if (ModelState.IsValid)
            {
                _context.Add(genre);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(genre);
        }

        // GET: Genres/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var genre = await _context.Genres.FindAsync(id);
            if (genre == null)
            {
                return NotFound();
            }
            return View(genre);
        }

        // POST: Genres/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] Genre genre)
        {
            if (id != genre.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(genre);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GenreExists(genre.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(genre);
        }

        // GET: Genres/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var genre = await _context.Genres
                .FirstOrDefaultAsync(m => m.Id == id);
            if (genre == null)
            {
                return NotFound();
            }

            return View(genre);
        }

        // POST: Genres/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var genre = await _context.Genres.FindAsync(id);
            if (genre != null)
            {
                _context.Genres.Remove(genre);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GenreExists(int id)
        {
            return _context.Genres.Any(e => e.Id == id);
        }
    }
}

CineTicketHub/Controllers/MoviesController.cs
using CineTicketHub.Enums;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using CineTicketHub.Mappers;
using CineTicketHub.Models.ViewModels;
using CineTicketHub.Services;
using CineTicketHub.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;

namespace CineTicketHub.Controllers
{
    public class MoviesController : Controller
    {
        private readonly IMoviesService _service;   
        private readonly IGenresService _genresService;
        private readonly MovieMapper _movieMapper;
        private readonly CineTicketHubContext _context;

        public MoviesController(IMoviesService service, IGenresService genresService, MovieMapper movieMapper, CineTicketHubContext context)
        {
            _context = context;
            _service = service;
            _genresService = genresService;
            _movieMapper = movieMapper;
        }

        // GET: Movies
        public async Task<IActionResult> Index()
        {
            var isContentManager = User.IsInRole(UserRole.CONTENT_MANAGER.ToString());
            
            if (isContentManager)
            {
                return View("ContentManagerIndex", await _service.GetAllAsync());
            }
            
            var currentDate = DateTime.Now;

            var playingNow = _context.Movies
                .Where(m => m.Screenings.Any(s => s.StartsAt >= currentDate))
                .Include(m => m.Genres)
                .ToList();

            var upcomingMovies = _context.Movies
                .Where(m => m.Screenings.Count == 0)
                .Include(m => m.Genres)
                .ToList();

            // You can pass these lists to the view or use a ViewModel
            ViewData["PlayingNow"] = playingNow;
            ViewData["UpcomingMovies"] = upcomingMovies;

            return View("CustomerIndex");
            
        }

        // GET: Movies/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _service.GetByIdAsync(id.Value);
            
            if (movie == null)
            {
                return NotFound();
            }
            ViewBag.screenings = _context.Screenings.Include(s => s.Room).Where(s => s.MovieId == id.Value && s.StartsAt >= DateTime.Now).ToList();
            return View(movie);
        }

        // GET: Movies/Create
        [Authorize(Roles = "CONTENT_MANAGER")]
        public IActionResult Create()
        {
            ViewData["GenreIds"] = new SelectList(_genresService.GetAllAsync().Result, "Id", "Name");
            return View();
        }

        // POST: Movies/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "CONTENT_MANAGER")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(MovieVM movieVM)
        {
            if (!ModelState.IsValid) return View(movieVM);
            await _service.AddMovieAsync(movieVM);
            return RedirectToAction(nameof(Index));
        }

        // GET: Movies/Edit/5
        [Authorize(Roles = "CONTENT_MANAGER")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _service.GetByIdAsync(id.Value);
            
            if (movie == null)
            {
                return NotFound();
            }
            
            ViewData["GenreIds"] = new SelectList(_genresService.GetAllAsync().Result, "Id", "Name");
            return View(_movieMapper.MapToMovieVM(movie));
        }

        // POST: Movies/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "CONTENT_MANAGER")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, MovieVM movieVM)
        {
            if (id != movieVM.Id)
            {
                return NotFound();
            }

            if (!ModelState.IsValid) return View(movieVM);
            
            await _service.UpdateMovieAsync(movieVM);
            return RedirectToAction(nameof(Index));
        }

        // GET: Movies/Delete/5
        [Authorize(Roles = "CONTENT_MANAGER")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = _service.GetByIdAsync(id.Value).Result;
            
            if (movie == null)
            {
                return NotFound();
            }

            return View(movie);
        }

        // POST: Movies/Delete/5
        [HttpPost, ActionName("Delete")]
        [Authorize(Roles = "CONTENT_MANAGER")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
        
    }
}

CineTicketHub/Controllers/ReservationsController.cs
using System.Security.Claims;
using CineTicketHub.Enums;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using CineTicketHub.Models;
using CineTicketHub.Models.Entities;
using Microsoft.AspNetCore.Authorization;

namespace CineTicketHub.Controllers
{
    public class ReservationsController : Controller
    {
        private readonly CineTicketHubContext _context;

        public ReservationsController(CineTicketHubContext context)
        {
            _context = context;
        }

        // GET: Reservations
        [Authorize]
        public async Task<IActionResult> Index()
        {
            var isContentManager = User.IsInRole(UserRole.CONTENT_MANAGER.ToString());

            List<Reservation> reservations;
            if (isContentManager)
            {
                reservations = _context.Reservations
                    .Include(r => r.User)
                    .Include(r => r.Screening.Movie)
                    .Include(r => r.Screening.Room)
                    .OrderByDescending(r => r.Screening.StartsAt)
                    .ToList();
            }
            else
            {
                var userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
                reservations = _context.Reservations
                    .Where(r => r.UserId == userId)
                    .Include(r => r.Screening.Movie)
                    .Include(r => r.Screening.Room)
                    .OrderByDescending(r => r.Screening.StartsAt)
                    .ToList();
            }
            
            return View(reservations);
        }

        // GET: Reservations/Delete/5
        [Authorize(Roles = "CONTENT_MANAGER")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reservation = await _context.Reservations
                .Include(r => r.Screening)
                .Include(r => r.Screening.Movie)
                .Include(r => r.Screening.Room)
                .Include(r => r.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (reservation == null)
            {
                return NotFound();
            }

            return View(reservation);
        }

        // POST: Reservations/Delete/5
        [HttpPost, ActionName("Delete")]
        [Authorize(Roles = "CONTENT_MANAGER")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var reservation = await _context.Reservations.FindAsync(id);
            if (reservation != null)
            {
                _context.Reservations.Remove(reservation);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        
    }
}

CineTicketHub/Controllers/RoomsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CineTicketHub.Models;
using CineTicketHub.Models.Entities;
using Microsoft.AspNetCore.Authorization;

namespace CineTicketHub.Controllers
{
    public class RoomsController : Controller
    {
        private readonly CineTicketHubContext _context;

        public RoomsController(CineTicketHubContext context)
        {
            _context = context;
        }

        // GET: Rooms
        [Authorize(Roles = "CONTENT_MANAGER")]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Rooms.ToListAsync());
        }

        // GET: Rooms/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var room = await _context.Rooms
                .FirstOrDefaultAsync(m => m.Id == id);
            if (room == null)
            {
                return NotFound();
            }

            return View(room);
        }

        // GET: Rooms/Create
        [Authorize(Roles = "CONTENT_MANAGER")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Rooms/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "CONTENT_MANAGER")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Capacity")] Room room)
        {
            if (ModelState.IsValid)
            {
                _context.Add(room);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(room);
        }

        // GET: Rooms/Edit/5
        [Authorize(Roles = "CONTENT_MANAGER")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var room = await _context.Rooms.FindAsync(id);
            if (room == null)
            {
                return NotFound();
            }
            return View(room);
        }

        // POST: Rooms/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "CONTENT_MANAGER")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Capacity")] Room room)
        {
            if (id != room.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(room);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RoomExists(room.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(room);
        }

        // GET: Rooms/Delete/5
        [Authorize(Roles = "CONTENT_MANAGER")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var room = await _context.Rooms
                .FirstOrDefaultAsync(m => m.Id == id);
            if (room == null)
            {
                return NotFound();
            }

            return View(room);
        }

        // POST: Rooms/Delete/5
        [HttpPost, ActionName("Delete")]
        [Authorize(Roles = "CONTENT_MANAGER")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var room = await _context.Rooms.FindAsync(id);
            if (room != null)
            {
                _context.Rooms.Remove(room);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RoomExists(int id)
        {
            return _context.Rooms.Any(e => e.Id == id);
        }
    }
}

CineTicketHub/Views/Shared/_AdminHeaderPartial.cshtml
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
        Genres
    </a>
    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
        <li><a asp-controller="Genres" asp-action="Index" class="dropdown-item">Index</a></li>
        <li><a asp-controller="Genres" asp-action="Create" class="dropdown-item">Create</a></li>
    </ul>
</li>
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
        Rooms
    </a>
    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
        <li><a asp-controller="Rooms" asp-action="Index" class="dropdown-item">Index</a></li>
        <li><a asp-controller="Rooms" asp-action="Create" class="dropdown-item">Create</a></li>
    </ul>
</li>
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
        Movies
    </a>
    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
        <li><a asp-controller="Movies" asp-action="Index" class="dropdown-item">Index</a></li>
        <li><a asp-controller="Movies" asp-action="Create" class="dropdown-item">Create</a></li>
    </ul>
</li>
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
        Screenings
    </a>
    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
        <li><a asp-controller="Screenings" asp-action="Index" class="dropdown-item">Index</a></li>
        <li><a asp-controller="Screenings" asp-action="Create" class="dropdown-item">Create</a></li>
    </ul>
</li>
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
        Content Managers
    </a>
    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
        <li><a class="dropdown-item" asp-controller="ContentManagers" asp-action="Index">Index</a></li>
        <li><a class="dropdown-item" asp-controller="ContentManagers" asp-action="Create">Create</a></li>
    </ul>
</li>
<li class="nav-item">
    <a class="nav-link" asp-controller="Reservations" asp-action="Index">Reservations</a>
</li>

CineTicketHub/Views/Shared/_ContentManagerHeaderPartial.cshtml
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
        Genres
    </a>
    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
        <li><a asp-controller="Genres" asp-action="Index" class="dropdown-item">Index</a></li>
        <li><a asp-controller="Genres" asp-action="Create" class="dropdown-item">Create</a></li>
    </ul>
</li>
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
        Rooms
    </a>
    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
        <li><a asp-controller="Rooms" asp-action="Index" class="dropdown-item">Index</a></li>
        <li><a asp-controller="Rooms" asp-action="Create" class="dropdown-item">Create</a></li>
    </ul>
</li>
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
        Movies
    </a>
    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
        <li><a asp-controller="Movies" asp-action="Index" class="dropdown-item">Index</a></li>
        <li><a asp-controller="Movies" asp-action="Create" class="dropdown-item">Create</a></li>
    </ul>
</li>
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
        Screenings
    </a>
    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
        <li><a asp-controller="Screenings" asp-action="Index" class="dropdown-item">Index</a></li>
        <li><a asp-controller="Screenings" asp-action="Create" class="dropdown-item">Create</a></li>
    </ul>
</li>
<li class="nav-item">
    <a class="nav-link" asp-controller="Reservations" asp-action="Index">Reservations</a>
</li>

CineTicketHub/Views/Shared/_CustomerHeaderPartial.cshtml
<li class="nav-item">
    <a class="nav-link" asp-controller="Movies" asp-action="Index">Movies</a>
</li>
<li class="nav-item">
    <a class="nav-link" asp-controller="Reservations" asp-action="Index">My Reservations</a>
</li>

CineTicketHub/Views/Shared/_HeaderPartial.cshtml
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CineTicketHub</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                
                    @{
                        if (User.Identity.IsAuthenticated)
                        {
                            if (User.IsInRole("ADMIN"))
                            {
                                @await Html.PartialAsync("_AdminHeaderPartial")
                            }
                            else if (User.IsInRole("CONTENT_MANAGER"))
                            {
                                @await Html.PartialAsync("_ContentManagerHeaderPartial")
                            }
                            else
                            {
                                @await Html.PartialAsync("_CustomerHeaderPartial")
                            }
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link active" asp-controller="Movies" asp-action="Index">Movies</a>
                            </li>
                        }
                    }
                
                </ul>
                
                <!-- Include the login partial view -->
                @await Html.PartialAsync("_LoginPartial")
                
            </div>
        </div>
    </nav>
</header>

CineTicketHub/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Mvc.RazorPages
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - CineTicketHub</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/CineTicketHub.styles.css" asp-append-version="true"/>
</head>
<body>

@await Html.PartialAsync("_HeaderPartial")

<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2024 - CineTicketHub - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>