CineTicketHub/Models/Entities/Screening.cs
namespace CineTicketHub.Models.Entities;

public partial class Screening
{
    public int Id { get; set; }

    public int MovieId { get; set; }

    public int RoomId { get; set; }

    public DateTime StartsAt { get; set; }

    public virtual Movie Movie { get; set; } = null!;

    public virtual ICollection<Reservation> Reservations { get; set; } = new List<Reservation>();

    public virtual Room Room { get; set; } = null!;
}

CineTicketHub/Models/Screening.cs
using System;
using System.Collections.Generic;

namespace CineTicketHub.Models;

public partial class Screening
{
    public int Id { get; set; }

    public int MovieId { get; set; }

    public int RoomId { get; set; }

    public DateTime StartsAt { get; set; }

    public virtual Movie Movie { get; set; } = null!;

    public virtual ICollection<Reservation> Reservations { get; set; } = new List<Reservation>();

    public virtual Room Room { get; set; } = null!;
}

CineTicketHub/Controllers/RoomsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CineTicketHub.Models;
using CineTicketHub.Models.Entities;
using Microsoft.AspNetCore.Authorization;

namespace CineTicketHub.Controllers
{
    public class RoomsController : Controller
    {
        private readonly CineTicketHubContext _context;

        public RoomsController(CineTicketHubContext context)
        {
            _context = context;
        }

        // GET: Rooms
        [Authorize(Roles = "CONTENT_MANAGER")]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Rooms.ToListAsync());
        }

        // GET: Rooms/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var room = await _context.Rooms
                .FirstOrDefaultAsync(m => m.Id == id);
            if (room == null)
            {
                return NotFound();
            }

            return View(room);
        }

        // GET: Rooms/Create
        [Authorize(Roles = "CONTENT_MANAGER")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Rooms/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "CONTENT_MANAGER")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Capacity")] Room room)
        {
            if (ModelState.IsValid)
            {
                _context.Add(room);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(room);
        }

        // GET: Rooms/Edit/5
        [Authorize(Roles = "CONTENT_MANAGER")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var room = await _context.Rooms.FindAsync(id);
            if (room == null)
            {
                return NotFound();
            }
            return View(room);
        }

        // POST: Rooms/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "CONTENT_MANAGER")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Capacity")] Room room)
        {
            if (id != room.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(room);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RoomExists(room.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(room);
        }

        // GET: Rooms/Delete/5
        [Authorize(Roles = "CONTENT_MANAGER")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var room = await _context.Rooms
                .FirstOrDefaultAsync(m => m.Id == id);
            if (room == null)
            {
                return NotFound();
            }

            return View(room);
        }

        // POST: Rooms/Delete/5
        [HttpPost, ActionName("Delete")]
        [Authorize(Roles = "CONTENT_MANAGER")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var room = await _context.Rooms.FindAsync(id);
            if (room != null)
            {
                _context.Rooms.Remove(room);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RoomExists(int id)
        {
            return _context.Rooms.Any(e => e.Id == id);
        }
    }
}

CineTicketHub/Controllers/ScreeningsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CineTicketHub.Enums;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CineTicketHub.Models;
using CineTicketHub.Models.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace CineTicketHub.Controllers
{
    
    public class ScreeningsController : Controller
    {
        private readonly CineTicketHubContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public ScreeningsController(CineTicketHubContext context, 
            UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Screenings
        [Authorize(Roles = "CONTENT_MANAGER")]
        public async Task<IActionResult> Index()
        {
            var screenings = _context.Screenings
                .Include(s => s.Movie)
                .Include(s => s.Room)
                .OrderByDescending(s => s.StartsAt)
                .ToList();
            
            return View(screenings);
        }

        // GET: Screenings/Details/5
        [Authorize(Roles = "CONTENT_MANAGER")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var screening = await _context.Screenings
                .Include(s => s.Movie)
                .Include(s => s.Room)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (screening == null)
            {
                return NotFound();
            }

            return View(screening);
        }

        // GET: Screenings/Create
        [Authorize(Roles = "CONTENT_MANAGER")]
        public IActionResult Create()
        {
            ViewData["MovieId"] = new SelectList(_context.Movies, "Id", "Title");
            ViewData["RoomId"] = new SelectList(_context.Rooms, "Id", "Name");
            return View();
        }

        // POST: Screenings/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "CONTENT_MANAGER")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,MovieId,RoomId,StartsAt")] Screening screening)
        {
            // Ignore the movie and room properties
            ModelState.Remove(nameof(Screening.Movie));
            ModelState.Remove(nameof(Screening.Room));
            
            // Check if the movie id exists
            if (!MovieExists(screening.MovieId))
                ModelState.AddModelError(nameof(Screening.MovieId), $"Movie with ID {screening.MovieId} does not exist.");
            
            // Check if the room id exists
            if (!RoomExists(screening.RoomId))
                ModelState.AddModelError(nameof(Screening.RoomId), $"Room with ID {screening.RoomId} does not exist.");
            
            if (!ModelState.IsValid)
            {
                ViewData["MovieId"] = new SelectList(_context.Movies, "Id", "Id", screening.MovieId);
                ViewData["RoomId"] = new SelectList(_context.Rooms, "Id", "Id", screening.RoomId);
                return View(screening);
            }
            
            _context.Add(screening);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        // GET: Screenings/Edit/5
        [Authorize(Roles = "CONTENT_MANAGER")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var screening = await _context.Screenings.FindAsync(id);
            if (screening == null)
            {
                return NotFound();
            }
            ViewData["MovieId"] = new SelectList(_context.Movies, "Id", "Title", screening.MovieId);
            ViewData["RoomId"] = new SelectList(_context.Rooms, "Id", "Name", screening.RoomId);
            return View(screening);
        }

        // POST: Screenings/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "CONTENT_MANAGER")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,MovieId,RoomId,StartsAt")] Screening screening)
        {
            if (id != screening.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(screening);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ScreeningExists(screening.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["MovieId"] = new SelectList(_context.Movies, "Id", "Title", screening.MovieId);
            ViewData["RoomId"] = new SelectList(_context.Rooms, "Id", "Name", screening.RoomId);
            return View(screening);
        }

        // GET: Screenings/Delete/5
        [Authorize(Roles = "CONTENT_MANAGER")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var screening = await _context.Screenings
                .Include(s => s.Movie)
                .Include(s => s.Room)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (screening == null)
            {
                return NotFound();
            }

            return View(screening);
        }

        // POST: Screenings/Delete/5
        [HttpPost, ActionName("Delete")]
        [Authorize(Roles = "CONTENT_MANAGER")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var screening = await _context.Screenings.FindAsync(id);
            if (screening != null)
            {
                _context.Screenings.Remove(screening);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        
        // GET: Screenings/{screeningId}/reservations
        [HttpGet]
        [Route("/screenings/{screeningId}/reservations/create")]
        [Authorize]
        public async Task<ViewResult> CreateReservation(int screeningId)
        {
            Reservation newReservation = new Reservation()
            {
                Screening = await _context.Screenings
                    .Include(s => s.Movie)
                    .Include(s => s.Room)
                    .FirstOrDefaultAsync(s => s.Id == screeningId)
            };
            ViewBag.SeatsLeft = seatsLeft(screeningId);
            return View(newReservation);
        }
        
        // GET: Screenings/{screeningId}/reservations
        [HttpPost]
        [Route("/screenings/{screeningId}/reservations/create")]
        [Authorize]
        public async Task<ActionResult> CreateReservation(int screeningId, [Bind("Screening, NumOfSeats")] Reservation reservation)
        {
            
            // Ignore the movie and room properties
            ModelState.Remove(nameof(Reservation.User));
            ModelState.Remove(nameof(Reservation.UserId));
            ModelState.Remove(nameof(Reservation.Screening));
            
            if (reservation.NumOfSeats <= 0)
                ModelState.AddModelError(nameof(Reservation.NumOfSeats), $"Invalid number of seats.");

            var availableSeats = seatsLeft(screeningId);
            
            if (reservation.NumOfSeats > availableSeats)
                ModelState.AddModelError(nameof(Reservation.NumOfSeats), $"Only {availableSeats} seats are left.");

            Screening currentScreening = await _context.Screenings
                .Include(s => s.Movie)
                .Include(s => s.Room)
                .FirstOrDefaultAsync(s => s.Id == screeningId);
            
            if (!ModelState.IsValid)
            {
                ViewBag.SeatsLeft = seatsLeft(screeningId);
                return View(new Reservation() { Screening = currentScreening });
            }
            
            var newReservation = new Reservation()
            {
                ScreeningId = screeningId,
                Screening = currentScreening,
                UserId = _userManager.GetUserId(User),
                NumOfSeats = reservation.NumOfSeats
            };
                
            await _context.Reservations.AddAsync(newReservation);
            await _context.SaveChangesAsync();
            
            // Pass the reservation model to the confirmation view
            return View("ConfirmReservation", newReservation);
        }

        private bool MovieExists(int id)
        {
            return _context.Movies.Any(m => m.Id == id);
        }

        private bool RoomExists(int id)
        {
            return _context.Rooms.Any(r => r.Id == id);
        }
        
        private bool ScreeningExists(int id)
        {
            return _context.Screenings.Any(e => e.Id == id);
        }

        private int seatsLeft(int screeningId)
        {
            var roomCap = _context.Screenings
                .Include(s => s.Room)
                .FirstOrDefault(s => s.Id == screeningId)

CineTicketHub/Views/Screenings/ConfirmReservation.cshtml
@model CineTicketHub.Models.Entities.Reservation

@{
    ViewBag.Title = "Reservation Confirmation";
}

<div class="container mt-4">
    <div class="row">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <h2 class="card-title">Reservation Confirmed</h2>
                    <p class="card-text">Thank you for reserving seats for: @Model.Screening.Movie.Title</p>
                </div>
            </div>
        </div>

        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <h3 class="card-title">Reservation Details</h3>
                    <hr />
                    <dl class="row">
                        <dt class="col-sm-4">Movie:</dt>
                        <dd class="col-sm-8">@Model.Screening.Movie.Title</dd>

                        <dt class="col-sm-4">Date and Time:</dt>
                        <dd class="col-sm-8">@Model.Screening.StartsAt.ToString("dd/MM/yyyy, HH:mm")</dd>

                        <dt class="col-sm-4">Room:</dt>
                        <dd class="col-sm-8">@Model.Screening.Room.Name</dd>

                        <dt class="col-sm-4">Reserved Seats:</dt>
                        <dd class="col-sm-8">@Model.NumOfSeats</dd>
                    </dl>

                    <p class="card-text">Your reservation has been confirmed. Enjoy the movie!</p>
                </div>
            </div>
        </div>
    </div>
</div>


<p><a href="@Url.Action("Index", "Movies")">Back to Movies</a></p>

CineTicketHub/Views/Screenings/Create.cshtml
@model CineTicketHub.Models.Entities.Screening

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Screening</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="MovieId" class="control-label">Movie</label>
                <select asp-for="MovieId" class ="form-control" asp-items="ViewBag.MovieId"></select>
                <span asp-validation-for="MovieId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RoomId" class="control-label">Room</label>
                <select asp-for="RoomId" class ="form-control" asp-items="ViewBag.RoomId"></select>
                <span asp-validation-for="RoomId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartsAt" class="control-label"></label>
                <input asp-for="StartsAt" class="form-control" />
                <span asp-validation-for="StartsAt" class="text-danger"></span>
            </div>
            <div class="form-group mt-2">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CineTicketHub/Views/Screenings/CreateReservation.cshtml
@model CineTicketHub.Models.Entities.Reservation

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container mt-4">
    <div class="row">
        <h2>Create a Reservation for: <a asp-controller="Movies" asp-action="Details" asp-route-id="@Model.Screening.MovieId">@Model.Screening.Movie.Title</a></h2>
        
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <img src="@Model.Screening.Movie.PosterUrl" class="img-fluid" alt="@Model.Screening.Movie.Title Poster" style="max-height: 70%">
                </div>
            </div>
        </div>

        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <h3 class="card-title">Screening Details</h3>
                    <hr />
                    <dl class="row">
                        <dt class="col-sm-4">Date and Time:</dt>
                        <dd class="col-sm-8">@Model.Screening.StartsAt.ToString("dd/MM/yyyy, HH:mm")</dd>

                        <dt class="col-sm-4">Room:</dt>
                        <dd class="col-sm-8"><a asp-controller="Rooms" asp-action="Details" asp-route-id="@Model.Screening.RoomId">@Model.Screening.Room.Name</a></dd>

                        <dt class="col-sm-4">Seats left:</dt>
                        <dd class="col-sm-8">@ViewBag.SeatsLeft</dd>
                    </dl>

                    @if (@ViewBag.SeatsLeft > 0)
                    {
                        <form asp-controller="Screenings" asp-action="CreateReservation" method="post">
                            <div class="form-group">
                                <label asp-for="NumOfSeats" class="control-label">Number of Seats:</label>
                                <input asp-for="NumOfSeats" class="form-control" placeholder="Enter number of seats"/>
                                <span asp-validation-for="NumOfSeats" class="text-danger"></span>
                            </div>

                            <input type="submit" value="Reserve Seats" class="btn btn-primary mt-2"/>
                        </form>
                    }
                    else
                    {
                        <input value="Sold out" class="btn btn-danger mt-2" disabled/>
                    }
                </div>
            </div>
        </div>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CineTicketHub/Views/Screenings/Delete.cshtml
@model CineTicketHub.Models.Entities.Screening

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Screening</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StartsAt)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartsAt)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Movie)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Movie.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Room)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Room.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

CineTicketHub/Views/Screenings/Details.cshtml
@model CineTicketHub.Models.Entities.Screening

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Screening</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StartsAt)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartsAt)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Movie)
        </dt>
        <dd class = "col-sm-10">
            <a asp-controller="Movies" asp-action="Details" asp-route-id="@Model.Movie.Id">
                @Html.DisplayFor(model => model.Movie.Title)
            </a>
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Room)
        </dt>
        <dd class="col-sm-10">
            <a asp-controller="Rooms" asp-action="Details" asp-route-id="@Model.Room.Id">
                @Html.DisplayFor(model => model.Room.Name)
            </a>
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

CineTicketHub/Views/Screenings/Edit.cshtml
@model CineTicketHub.Models.Entities.Screening

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Screening</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="MovieId" class="control-label">Movie</label>
                <select asp-for="MovieId" class="form-control" asp-items="ViewBag.MovieId"></select>
                <span asp-validation-for="MovieId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RoomId" class="control-label">Room</label>
                <select asp-for="RoomId" class="form-control" asp-items="ViewBag.RoomId"></select>
                <span asp-validation-for="RoomId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartsAt" class="control-label"></label>
                <input asp-for="StartsAt" class="form-control" />
                <span asp-validation-for="StartsAt" class="text-danger"></span>
            </div>
            <div class="form-group mt-2">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CineTicketHub/Views/Screenings/Index.cshtml
@model IEnumerable<CineTicketHub.Models.Entities.Screening>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.StartsAt)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Movie)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Room)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.StartsAt)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Movie.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Room.Name)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>